apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zcp-iam
  namespace: zcp-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: zcp-iam
    spec:
      tolerations:
      - key: "management"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - "amd64"
              - key: role
                operator: In
                values:
                - "management"
      containers:
      - name: zcp-iam
        image: cloudzcp/zcp-iam
        imagePullPolicy: Always
        ports:
        - name: cont-port
          containerPort: 8181
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "800m"
        envFrom:
        - configMapRef:
            name: zcp-iam-config
        env:
          - name: KEYCLOAK_MASTER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: zcp-iam-secret
                key: KEYCLOAK_MASTER_CLIENT_SECRET
          - name: KEYCLOAK_MASTER_USERNAME
            valueFrom:
              secretKeyRef:
                name: zcp-iam-secret
                key: KEYCLOAK_MASTER_USERNAME
          - name: KEYCLOAK_MASTER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zcp-iam-secret
                key: KEYCLOAK_MASTER_PASSWORD
      serviceAccount: zcp-system-admin
      serviceAccountName: zcp-system-admin
---

apiVersion: v1
kind: Service
metadata:
  name: zcp-iam
  labels:
    name: zcp-iam
  namespace: zcp-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: "cont-port"
    protocol: TCP
    name: http
  selector:
    component: zcp-iam

