apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: ibmc-block-retain-silver
  labels:
    billingType: "hourly"
  name: zcp-iam-mongodb
  namespace: zcp-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
